menu:
  Home:
  Archives: archives
  About: about

widgets:
- search
- category
- tag

excerpt_link: Read More

twitter: 
  username: ruimsramos
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid: 
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: false

google_analytics: UA-106053129-1
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 524446951221420
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
